name: Update WP-CLI Commands List
on:
    workflow_dispatch:
    schedule:
    # Once a day at 6am
    - cron: "0 6 * * *"
jobs:
    wp-cli:
        name: WP CLI Commands List
        runs-on: ubuntu-latest
        permissions:
            contents: write
        strategy:
            fail-fast: true
        steps:
            - name: Check out source code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  tools: wp-cli

            - name: Generate WP-CLI Commands List
              run: wp cli cmd-dump > ${{ github.workspace }}/cli/data/wpcli-commands.json
              
            - name: Get WP-CLI version
              run: wp --version > ${{ github.workspace }}/cli/data/wpcli-version.txt

            - name: Commit any changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: 'Update WP-CLI Commands List'
                  commit_options: '--no-verify'
                  commit_user_name: 'GitHub Actions'
                  commit_user_email: 'github-actions[bot]@users.noreply.github.com'
                  commit_author: 'GitHub Actions <github-actions[bot]@users.noreply.github.com>'
